### ISSUE TITLE
Please convey this error

### ISSUE THREAD

**Issue by jennierj05** [DEV-D-GR8/SignSense#1]
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[29], line 1
----> 1 X_train = np.load(f'GISLR/X.npy')
      2 y_train = np.load(f'GISLR/y.npy')
      3 NON_EMPTY_FRAME_IDXS_TRAIN = np.load(f'GISLR/NON_EMPTY_FRAME_IDXS.npy')

File C:\Program Files\Python\lib\site-packages\numpy\lib\npyio.py:405, in load(file, mmap_mode, allow_pickle, fix_imports, encoding, max_header_size)
    403     own_fid = False
    404 else:
--> 405     fid = stack.enter_context(open(os_fspath(file), "rb"))
    406     own_fid = True
    408 # Code to distinguish from NumPy binary files and pickles.

FileNotFoundError: [Errno 2] No such file or directory: 'GISLR/X.npy'

**Comment by DEV-D-GR8** [comment]
You have to first download the dataset and then proceed to process it.
The "npy" files are intermediate processed files of the original dataset that I saved for later reference. If you proceed to just copy and paste the code to run on your system, you can even skip that with certain tweaks in the code.
